import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

// import localFont from "next/font/local";
// const campton = localFont({
//   src: "./assets/fonts/Campton/",
//   display: "swap",
// });
// const arsseit = localFont({
//   src: "./assets/fonts/Larsseit ",
//   display: "swap",
// });
// const quincy = localFont({
//   src: "./assets/fonts/Quincy",
//   display: "swap",
// });
// const quincyCF = localFont({
//   src: "./assets/fonts/QuincyCF",
//   display: "swap",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>{children}</body>
    </html>
  );
}
