const colors = {
  oak: "rgb(221, 181, 134)",
  walnut: "rgb(88, 47, 17)",
  blackWood: "rgb(10, 4, 1)",
  espresso: "rgb(68, 33, 9)",
  twilight: "rgb(153, 153, 153)",
  solstice: "rgb(248, 248, 248)",
  eclipse: "rgb(29, 29, 29)",
};

export const allCozyTables = [
  {
    title: "Coffee Tables",
    id: "coffeeTables",
    tables: [
      {
        id: 1,
        img: "/Cozey-Assets/Coffee-Tables/coffeeTable1.webp",
        text: "Stella Coffee Table - 1 Unit",
        subtext: "$420 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
      {
        id: 2,
        img: "/Cozey-Assets/Coffee-Tables/coffeeTable2.webp",
        text: "Stella Coffee Table - 2 Units",
        subtext: "$210 or financing |",
        typeOfWood: "Walnut",
        color: colors.walnut,
      },
      {
        id: 3,
        img: "/Cozey-Assets/Coffee-Tables/coffeeTable3.webp",
        text: "Pluto Coffee Table",
        subtext: "$135 or financing |",
        typeOfWood: "Black Wood",
        color: colors.blackWood,
      },
      {
        id: 4,
        img: "/Cozey-Assets/Coffee-Tables/coffeeTable4.webp",
        text: "Stella Coffee Table - 3 Units",
        subtext: "$630 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
      {
        id: 5,
        img: "/Cozey-Assets/Coffee-Tables/coffeeTable5.webp",
        text: "Pluto Coffee Table",
        subtext: "$135 or financing |",
        typeOfWood: "Espresso",
        color: colors.espresso,
      },
      {
        id: 6,
        img: "/Cozey-Assets/Coffee-Tables/coffeeTable6.webp",
        text: "Stella Coffee Table - 1 Unit",
        subtext: "$210 or financing |",
        typeOfWood: "Walnut",
        color: colors.walnut,
      },
      {
        id: 7,
        img: "/Cozey-Assets/Coffee-Tables/coffeeTable7.webp",
        text: "Stella Coffee Table - 2 Units",
        subtext: "$420 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
      {
        id: 8,
        img: "/Cozey-Assets/Coffee-Tables/coffeeTable8.webp",
        text: "Stella Coffee Table - 3 Units",
        subtext: "$630 or financing |",
        typeOfWood: "Walnut",
        color: colors.walnut,
      },
    ],
  },
  {
    title: "Side Tables",
    id: "sideTables",
    tables: [
      {
        id: 1,
        img: "/Cozey-Assets/side-Tables/sideTable1.webp",
        text: "Solis Adjustable Table",
        subtext: "$180 or financing |",
        typeOfWood: "Eclipse",
        color: colors.eclipse,
      },
      {
        id: 2,
        img: "/Cozey-Assets/Side-Tables/sideTable2.webp",
        text: "Solis Adjustable Table",
        subtext: "$180 or financing |",
        typeOfWood: "Twilight",
        color: colors.twilight,
      },
      {
        id: 3,
        img: "/Cozey-Assets/Side-Tables/sideTable3.webp",
        text: "Solis Adjustable Table",
        subtext: "$180 or financing |",
        typeOfWood: "Solstice",
        color: colors.solstice,
      },
      {
        id: 4,
        img: "/Cozey-Assets/Side-Tables/sideTable4.webp",
        text: "Stella Coffee Table - 1 Unit",
        subtext: "$210 or financing |",
        typeOfWood: "Walnut",
        color: colors.walnut,
      },
      {
        id: 5,
        img: "/Cozey-Assets/Side-Tables/sideTable5.webp",
        text: "Stella Coffee Table - 1 Unit",
        subtext: "$210 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
      {
        id: 6,
        img: "/Cozey-Assets/Side-Tables/sideTable6.webp",
        text: "Pluto Side Table",
        subtext: "$85 or financing |",
        typeOfWood: "Espresso",
        color: colors.espresso,
      },
      {
        id: 7,
        img: "/Cozey-Assets/Side-Tables/sideTable7.webp",
        text: "Pluto Side Table",
        subtext: "$85 or financing |",
        typeOfWood: "Black Wood",
        color: colors.oak,
      },
      {
        id: 8,
        img: "/Cozey-Assets/Side-Tables/sideTable8.webp",
        text: "Stella Media Unit - 1 Unit | No Door",
        subtext: "$145 or financing |",
        typeOfWood: "Walnut",
        color: colors.walnut,
      },
      {
        id: 9,
        img: "/Cozey-Assets/Side-Tables/sideTable9.webp",
        text: "Stella Media Unit - 1 Unit | No Door",
        subtext: "$145 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
      {
        id: 10,
        img: "/Cozey-Assets/Side-Tables/sideTable10.webp",
        text: "Stella Media Unit - 1 Unit | With Door",
        subtext: "$165 or financing |",
        typeOfWood: "Walnut",
        color: colors.walnut,
      },
      {
        id: 11,
        img: "/Cozey-Assets/Side-Tables/sideTable11.webp",
        text: "Stella Media Unit - 1 Unit | With Door",
        subtext: "$165 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
    ],
  },
  {
    title: "Media Units",
    id: "mediaUnits",
    tables: [
      {
        id: 1,
        img: "/Cozey-Assets/Media-Units/mediaUnit1.webp",
        text: "Stella Media Unit - 3 Units",
        subtext: "$475 or financing |",
        typeOfWood: "Walnut",
        color: colors.walnut,
      },
      {
        id: 2,
        img: "/Cozey-Assets/Media-Units/mediaUnit2.webp",
        text: "Stella Media Unit - 2 Units | With Doors",
        subtext: "$330 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
      {
        id: 3,
        img: "/Cozey-Assets/Media-Units/mediaUnit3.webp",
        text: "Stella Media Unit - 1 Unit | With Door",
        subtext: "$165 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
      {
        id: 4,
        img: "/Cozey-Assets/Media-Units/mediaUnit4.webp",
        text: "Stella Media Unit - 1 Unit | No Door",
        subtext: "$145 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
      {
        id: 5,
        img: "/Cozey-Assets/Media-Units/mediaUnit5.webp",
        text: "Stella Media Unit - 2 Units",
        subtext: "$310 or financing |",
        typeOfWood: "Walnut",
        color: colors.walnut,
      },
      {
        id: 6,
        img: "/Cozey-Assets/Media-Units/mediaUnit6.webp",
        text: "Stella Media Unit - 2 Units | No Doors",
        subtext: "$290 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
      {
        id: 7,
        img: "/Cozey-Assets/Media-Units/mediaUnit7.webp",
        text: "Stella Media Unit - 3 Units",
        subtext: "$475 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
      {
        id: 8,
        img: "/Cozey-Assets/Media-Units/mediaUnit8.webp",
        text: "Stella Media Unit - 3 Units | No Doors",
        subtext: "$435 or financing |",
        typeOfWood: "Walnut",
        color: colors.walnut,
      },
      {
        id: 9,
        img: "/Cozey-Assets/Media-Units/mediaUnit9.webp",
        text: "Stella Media Unit - 4 Units",
        subtext: "$620 or financing |",
        typeOfWood: "Walnut",
        color: colors.walnut,
      },
      {
        id: 10,
        img: "/Cozey-Assets/Media-Units/mediaUnit10.webp",
        text: "Stella Media Unit - 4 Units | No Doors",
        subtext: "$580 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
      {
        id: 11,
        img: "/Cozey-Assets/Media-Units/mediaUnit11.webp",
        text: "Stella Media Unit - 2 Units",
        subtext: "$310 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
      {
        id: 12,
        img: "/Cozey-Assets/Media-Units/mediaUnit12.webp",
        text: "Stella Media Unit - 4 Units",
        subtext: "$620 or financing |",
        typeOfWood: "Walnut",
        color: colors.walnut,
      },
      {
        id: 13,
        img: "/Cozey-Assets/Media-Units/mediaUnit13.webp",
        text: "Stella Media Unit - 3 Units | With Doors",
        subtext: "$495 or financing |",
        typeOfWood: "Walnut",
        color: colors.walnut,
      },
      {
        id: 14,
        img: "/Cozey-Assets/Media-Units/mediaUnit14.webp",
        text: "Stella Media Unit - 4 Units | With Doors",
        subtext: "$660 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
    ],
  },
  {
    title: "Table Sets",
    id: "tableSets",
    tables: [
      {
        id: 1,
        img: "/Cozey-Assets/Table-Sets/tableSet1.webp",
        text: "Pluto Table Set | 1 Coffee Table & 1 Side Table",
        subtext: "$195 or financing |",
        typeOfWood: "Black Wood",
        color: colors.blackWood,
      },
      {
        id: 2,
        img: "/Cozey-Assets/Table-Sets/tableSet2.webp",
        text: "Pluto Table Set | 1 Coffee Table & 2 Side Table",
        subtext: "$255 or financing |",
        typeOfWood: "Espresso",
        color: colors.espresso,
      },
      {
        id: 3,
        img: "/Cozey-Assets/Table-Sets/tableSet3.webp",
        text: "Pair of Solis Adjustable Tables",
        subtext: "$320 or financing |",
        typeOfWood: "Eclipse",
        color: colors.eclipse,
      },
      {
        id: 4,
        img: "/Cozey-Assets/Table-Sets/tableSet4.webp",
        text: "Stella Table Set | 2-Unit Media & 2-Unit Coffee Table",
        subtext: "$505 or financing |",
        typeOfWood: "Walnut",
        color: colors.walnut,
      },
      {
        id: 5,
        img: "/Cozey-Assets/Table-Sets/tableSet5.webp",
        text: "Stella Table Set | 2-Unit Media & 1 Side Table",
        subtext: "$180 or financing |",
        typeOfWood: "Walnut",
        color: colors.walnut,
      },
      {
        id: 6,
        img: "/Cozey-Assets/Table-Sets/tableSet6.webp",
        text: "Stella Table Set | 3-Unit Media & 2-Unit Coffee Table",
        subtext: "$715 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
      {
        id: 7,
        img: "/Cozey-Assets/Table-Sets/tableSet7.webp",
        text: "Stella Table Set | 3-Unit Media & 1 Side Table",
        subtext: "$580 or financing |",
        typeOfWood: "Oak",
        color: colors.oak,
      },
    ],
  },
];
